import { test, expect } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

test('test', async ({ page }) => {
  await page.goto('https://localhost:5959/login');
  await page.getByRole('textbox', { name: 'Username' }).fill(process.env.USERNAME!);
  await page.getByRole('textbox', { name: 'Password' }).fill(process.env.PASSWORD!);
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByText('Manage & Govern Identities').click();
  await page.getByRole('button', { name: 'Add Source' }).click();

  await page.getByText('Volt HRMS').click({ force: true });
  await page.locator('#identity_name').fill('volt hrms');
  await page.locator('#start_range').fill('SINDHUJA7FYHPL3\\SQLEXPRESS');
  await page.locator('#default_database').fill('iga');

  await page.setInputFiles('input[type="file"]', 'Testing_upload_documents/volt_hrms.yaml');

  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Next' }).click();

  await page.locator('#credential_username').fill(process.env.HRMS_USERNAME!);
  await page.locator('#credential_password').fill(process.env.HRMS_PASSWORD!);

  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByRole('gridcell', { name: 'volt hrms', exact: true }).dblclick();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByText('Manage & Govern Identities').click();
  await page.getByRole('link', { name: 'Applications' }).click();
  await page.getByRole('button', { name: 'Add Application' }).click();
  await page.getByText('AWS IAM').click({ force: true });
  await page.locator('#app_name').fill('AWS IAM');
  await page.locator('#app_name').press('Tab');
  await page.locator('#app_desc').press('Tab');
  await page.locator('#app_code').fill('C001');
  await page.locator('#app_code').press('Tab');
  await page.locator('#adImportForm').getByText('Securden Administrator').click();
  await page.locator('#client_id').click();
  await page.locator('#client_id').fill(process.env.CLIENT_ID!);
  await page.locator('#client_secret').click();
  await page.locator('#client_secret').fill(process.env.CLIENT_SECRET!);
  await page.getByRole('button', { name: 'Browse Choose a file' }).click();
  await page.setInputFiles('input[type="file"]', 'Testing_upload_documents/aws_iam.yaml');
  await page.locator('#yaml-edit-form').getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Applications' }).click();
  await page.getByRole('button', { name: 'Add Application' }).click();
  await page.getByText('Entra ID').click();
  await page.locator('#app_name').fill('Entra ID');
  await page.locator('#app_name').press('Tab');
  await page.locator('#app_desc').press('Tab');
  await page.locator('#app_code').fill('C003');
  await page.locator('#app_code').press('Tab');
  await page.locator('#addIgaAzureApplicationForm').getByText('Securden Administrator').click();
  await page.locator('#tenant_id').click();
  await page.locator('#tenant_id').fill(process.env.AZURE_TENANT_ID!);
  await page.locator('#client_id').click();
  await page.locator('#client_id').fill(process.env.AZURE_CLIENT_ID!);
  await page.locator('#client_secret').click();
  await page.locator('#client_secret').fill(process.env.AZURE_CLIENT_SECRET!);
  await page.getByRole('button', { name: 'Browse Choose a file' }).click();
  await page.setInputFiles('input[type="file"]', 'Testing_upload_documents/entra_id.yaml');
  await page.locator('#yaml-edit-form').getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Applications' }).click();
  await page.getByRole('button', { name: 'Add Application' }).click();
  await page.getByText('Exchange Server').click();
  await page.locator('#app_name').fill('Exchange server onprem');
  await page.locator('#app_name').press('Tab');
  await page.locator('#app_desc').press('Tab');
  await page.locator('#app_code').fill('A002');
  await page.locator('#app_code').press('Tab');
  await page.locator('#start_range').fill('192.168.1.27');
  await page.locator('.cyb-dropdown-label').first().click();
  await page.locator('#primary-accounts-discovery-form').getByText('Securden Administrator').click();
  await page.getByText('Select Autehntication Type *').click();
  await page.getByText('Basic', { exact: true }).click();
  await page.locator('#ssl-checkbox-status').click();
  await page.getByRole('button', { name: 'Browse Choose a file' }).click();
  await page.setInputFiles('input[type="file"]', 'Testing_upload_documents/exchange_onprem.yaml');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('#credential_username').click();
  await page.locator('#credential_username').fill(process.env.EXCHANGE_ONPREM_USERNAME!);
  await page.locator('#credential_username').press('Tab');
  await page.locator('#credential_password').fill(process.env.EXCHANGE_ONPREM_PASSWORD!);
  await page.getByRole('button', { name: 'Next' }).click();
  const baseDnField = page.getByText('Base DN').locator('..').locator('input');
  await expect(baseDnField).toBeVisible();
  await baseDnField.fill('OU=IGA,DC=example,DC=com');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Applications' }).click();
  await page.getByRole('button', { name: 'Add Application' }).click();
  await page.getByText('AWS Identity Center').click({ force: true });
  await page.locator('#app_name').click();
  await page.locator('#app_name').fill('AWS Identity Center');
  await page.locator('#app_name').press('Tab');
  await page.locator('#app_desc').press('Tab');
  await page.locator('#app_code').fill('C002');
  await page.locator('#app_code').press('Tab');
  await page.locator('#adImportForm').getByText('Securden Administrator').click();
  await page.getByRole('button', { name: 'Browse Choose a file' }).click();
  await page.setInputFiles('input[type="file"]', 'Testing_upload_documents/aws_cloud.yaml');
  await page.locator('#yaml-edit-form').getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Applications' }).click();
  await page.getByRole('button', { name: 'Add Application' }).click();
  await page.getByText('Exchange Cloud').click();
  await page.locator('#app_name').click();
  await page.locator('#app_name').fill('Exchange Cloud');
  await page.locator('#app_name').press('Tab');
  await page.locator('#app_desc').press('Tab');
  await page.locator('#app_code').fill('C004');
  await page.locator('#app_code').press('Tab');
  await page.locator('#addIgaAzureApplicationForm').getByText('Securden Administrator').click();
  await page.getByRole('button', { name: 'Browse Choose a file' }).click();
  await page.setInputFiles('input[type="file"]', 'Testing_upload_documents/exchange_cloud.yaml');
  await page.locator('#yaml-edit-form').getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Applications' }).click();
  await page.getByRole('button', { name: 'Add Application' }).click();
  await page.getByText('Active Directory').click();
  await page.locator('#app_name').fill('Securden AD Domain');
  await page.locator('#app_name').press('Tab');
  await page.locator('#app_desc').press('Tab');
  await page.locator('#app_code').fill('A001');
  await page.locator('#app_code').press('Tab');
  await page.locator('#start_range').fill('192.168.1.241');
  await page.locator('.cyb-dd.add-account-type > .cyb-dropdown-label').click();
  await page.locator('#primary-accounts-discovery-form').getByText('Securden Administrator').click();
  await page.getByRole('button', { name: 'Browse Choose a file' }).click();
  await page.setInputFiles('input[type="file"]', 'Testing_upload_documents/active_directory.yaml');
  await page.locator('#yaml-edit-form').getByRole('button', { name: 'Save' }).click();
  await page.locator('#credential_username').click();
  await page.locator('#credential_username').fill(process.env.AD_USERNAME!);
  await page.locator('#credential_username').press('Tab');
  await page.locator('#credential_password').fill(process.env.AD_PASSWORD!);
  await page.getByRole('button', { name: 'Next' }).click();
  const usersOuDropdown = page.getByText('Users OU').locator('..').locator('.cyb-dropdown-label');
  await expect(usersOuDropdown).toBeVisible();
  await usersOuDropdown.click();
  await page.getByText('OU=IGA', { exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Applications' }).click();
  await page.getByRole('button', { name: 'Add Application' }).click();
  await page.getByText('Office').click();
  await page.locator('#app_name').click();
  await page.locator('#app_name').fill('Office 365');
  await page.locator('#app_name').press('Tab');
  await page.locator('#app_desc').press('Tab');
  await page.locator('#app_code').fill('C005');
  await page.locator('#app_code').press('Tab');
  await page.locator('#addIgaAzureApplicationForm').getByText('Securden Administrator').click();
  await page.getByRole('button', { name: 'Browse Choose a file' }).click();
  await page.setInputFiles('input[type="file"]', 'Testing_upload_documents/entra_id.yaml');
  await page.locator('#yaml-edit-form').getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
});






